---
title: The Business Model
desc: What is a Business model and how to design one
slides: true
---
:h2 Logistics

* Attendance
* Preview of :topic_link :hw_102_pirate_metrics

:topic_include :ch9

:slide_bigtitle Business Models

* What did you learn about what a \"business model\" is? 
* You describe an idea you have and a friend asks you, what's the business model?
* What is your answer?

:topic_include :business_model_intro

:topic_include :bm_canvas

:lecture_end