---
title: In Class Quiz
desc: Covering the Lean Startup
---
:slide_bigtitle Quiz

* In class Latte Quiz
* True/False, Multiple Choice and Short Answers
* Scored as "Meets" vs. "Doesn't Meet Expectations"
* 55 minutes / TBD questions

:slide Topics

* MVP, idea, approach, reasoning, explanations
* Pivot, idea, approach, reasoning, explanations
* Engines of growth, idea, approach, reasoning, explanations
* Synthesis of all of the above in looking at scenarios




