---
title: Marketing
desc: How marketing fits into the Lean Startup
slides: true
---
:slide_title Logistics

:slide_title What is Marketing?

* i.e. vs. Sales?
* Simple way to think about it:
* Marketing: Demand Generation
* Sales: Demand Satisfaction

:slide_title "Growth Hacking"

* Intersection of engieering and marketing

:slide_title How does it fit in?

* How we describe our business to the world
* Positioning: "[our product] provides [solutions] to [target users] who are [specific segments]

:slide_title Elevator Pitch

* :topic_link :elevator_pitch
* :topic_link :elevator_pitch_exercise

:slide_title Marketing Tactics

* Non-product activities to drive the metrics you care about
* May often be for specific segments
* Will cost money (or loss of revenue)
* Need to be based on a hypothesis
* Their impact need to be measurable
* A later form of Validated Learning

:slide_title Examples of Tactices

* Creating and refining your online presence
* Recommendar Programs
* Advertising

:slide_title Ecosystem

* What alternatives are there for customers with those pain points?
* How are you different/better than them (along any dimension at all)
* Requires research about the products
* There are many online tools (including LLMs) to help with this

:slide_title Competitive Grid

* A simple way to illustrate how your product fits within the ecosystem
* Very commonly used
* Of course (because marketing) you paint your product in the best light

:lecture_end
