---
title: Operational Model
desc: How to actually build a financial model
slides: true
---
* **Video**: [Funding Stragegies](https://youtu.be/MuTdS29M1o4?si=bQ0966sYoRrKa9qx&t=6)

*Reminder: Readings and videos are your responsibility. You will be expected to come to class prepared, having read or viewed the material, and ready to participate in the discussion*

:topic_include :building_financial_model

:lecture_end

