---
title: The Business Model
desc: What is a Business model and how to design one
slides: true
---
:slide_bigtitle Speaker: Fiza Shaukat
:image :450, :fizashaukat

:slide_bigtitle Business Models

* What did you learn about what a \"business model\" is? 
* You describe an idea you have and a friend asks you, what's the business model?
* What is your answer?

:topic_include :business_model_intro

:topic_include :bm_canvas

:lecture_end