---
title: Metrics and Growth
desc: How metrics and growth are connected
slides: true
---
* **READING**: :topic_link :hw_102_leanstartup_10

*Reminder: Readings are your responsibility. You will be expected to come to class prepared, having read the material, and ready to participate in the discussion*

:topic_include :funnel

:topic_include :tuning_engine_of_growth

:topic_include :pirate_metrics

