---
title: Scientific Method
desc: How LS approaches experimentation and testing
cat: Product Management
slides: true
---
* **READING**: :topic_link :hw_102_leanstartup_6
* **READING**: :topic_link :hw_102_leanstartup_7

*Reminder: Readings are your responsibility. You will be expected to come to class prepared, having read the material, and ready to participate in the discussion*

:h2 Logistics

:topic_include :ls_hypotheses
:topic_include :ls_outofbuilding
:lecture_end
