---
title: Growth Hacking
desc: What is growth hacking and how does it work?
slides: true
---
:h2 Summary of feedback 
* **By Far: You really like real world stories, examples, scenarios and want more of them.**
* People also liked highly interactive class discussions, brainstorming, problems solving and want more of them
* Some of you want more detailed feedback on the assignments
* Several of you didn't like how the reading of TLS were bunched at the start
* There was some concern about grading and worries about that. A request to make grading extra lenient.
* There was some concern about scheduling of homeworks, overlapping and so on.

* Here is the [Raw Data](https://docs.google.com/spreadsheets/d/17-jDj99kerDSXbIDZiM5Ip0kvF6EvPKGUUusLW6vIjM/edit?usp=sharing)

:topic_include :growth_hacking_summary

:topic_include :pirate_metrics

:lecture_end 

