---
title: Intellectual Property
desc: Patents, Licenses and Secrecy
slides: true
---
:slide_title Reminders

* Reminder that final report will be one pdf not four separate ones
* Reminder you will be giving formal presentations during class time on December 3 and 6, at 11:10, in this room

:slide_title Tips for Stage3 from samples of Stage2
* In most cases they are not coordinated at all with each other
* In some cases they outright contradict each other
* In other cases the same information appears in detail in two places
* Include more evidence!! e.g. "Our target market is people with young children". (Because? What do you base that on?)
* Remember the ChatGPT policy!
* You cannot put a chatgpt generated screen design into your proposal!
* Generalization: tighten up your writing. I know "If I had more time I could have made it shorter".
* Beware of restating the same thing or saying in 20 words what you could say in 10
* Try to keep paragraphs below ~200 words (this is not a rule)
* Check your pdf before submitting! It may have rendered funny

:topic_include :ip

:topic_include :ip_definitions

:topic_include :ip_additional_topics

:lecture_end
